# Generated by Django 5.2.12 on 2026-03-05 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount_raised', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaunchEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('X', 'X'), ('LinkedIn', 'LinkedIn'), ('Crunchbase', 'Crunchbase')], max_length=50)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('engagement_status', models.CharField(choices=[('Good', 'Good'), ('Poor', 'Poor')], default='Good', max_length=10)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launches', to='api.company')),
            ],
        ),
    ]
