# Generated by Django 5.2.12 on 2026-03-05 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('linkedin_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('x_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='DM_Draft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_platform', models.CharField(choices=[('X', 'X'), ('LinkedIn', 'LinkedIn')], max_length=10)),
                ('draft_text', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_drafts', to='api.company')),
            ],
        ),
    ]
