# Generated by Django 5.2.12 on 2026-03-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_company_description_company_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launchevent',
            name='engagement_status',
        ),
        migrations.AddField(
            model_name='launchevent',
            name='last_monitored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launchevent',
            name='post_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
